version: '3.7'

services:
    ticket-world-mysql:
        image: mysql:8.0.35
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - ticket-world-mysql:/var/lib/mysql

    ticket-world-redis:
        image: redis:latest
        restart: always
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        expose:
            - "6379"
        ports:
            - "6379:6379"
        volumes:
            - ticket-world-redis:/data

    ticket-world-zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    ticket-world-kafka:
        image: confluentinc/cp-kafka:7.4.0
        depends_on:
            - ticket-world-zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "ticket-world-zookeeper:2181"

            # 외부에서 접속할 수 있도록 ADVERTISED_LISTENERS 설정
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
            KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"

            # 테스트 용도: 자동으로 토픽 생성 허용
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

            # 내부 토픽(replication factor) 관련 설정
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1

volumes:
    ticket-world-redis:
    ticket-world-mysql:
